In [17]:
import sqlite3
import pandas as pd

In [18]:
# Replace 'your_database_file.sqlite' with the actual name of your SQLite database file.
conn = sqlite3.connect(r'C:\Users\PC\Downloads\Moringa School\dsc-phase-1-project-v2-4\zippedData\im.db')

In [19]:
# Create a cursor object to interact with the database.
cursor = conn.cursor()

In [20]:
# Execute an SQL query
cursor.execute('SELECT * FROM persons')

# Fetch and print the result
result = cursor.fetchall()
result

[('nm0061671',
  'Mary Ellen Bauder',
  None,
  None,
  'miscellaneous,production_manager,producer'),
 ('nm0061865',
  'Joseph Bauer',
  None,
  None,
  'composer,music_department,sound_department'),
 ('nm0062070', 'Bruce Baum', None, None, 'miscellaneous,actor,writer'),
 ('nm0062195',
  'Axel Baumann',
  None,
  None,
  'camera_department,cinematographer,art_department'),
 ('nm0062798',
  'Pete Baxter',
  None,
  None,
  'production_designer,art_department,set_decorator'),
 ('nm0062879',
  'Ruel S. Bayani',
  None,
  None,
  'director,production_manager,miscellaneous'),
 ('nm0063198', 'Bayou', None, None, 'actor'),
 ('nm0063432', 'Stevie Be-Zet', None, None, 'composer,soundtrack'),
 ('nm0063618',
  'Jeff Beal',
  1963.0,
  None,
  'composer,music_department,soundtrack'),
 ('nm0063750', 'Lindsay Beamish', None, None, 'actress,miscellaneous'),
 ('nm0064023', 'Bryan Beasley', None, None, 'director,producer,writer'),
 ('nm0064350',
  'Martine Beauchemin',
  None,
  None,
  'producer,production_manager'),
 ('nm0065847',
  'Michael Frost Beckner',
  1963.0,
  None,
  'writer,producer,miscellaneous'),
 ('nm0065919',
  'Will Becton',
  None,
  None,
  'miscellaneous,editor,editorial_department'),
 ('nm0066093', 'Ahmad Bedair', 1945.0, None, 'actor,miscellaneous'),
 ('nm0066163', 'Arnaud Bedouët', None, None, 'actor,writer,director'),
 ('nm0066268',
  'Steve Mitchell Beebe',
  None,
  None,
  'editorial_department,director,editor'),
 ('nm0066897', 'Mohammad-Ali Behboudi', 1956.0, None, 'actor'),
 ('nm0067234', 'Hans Beimler', None, None, 'producer,writer,miscellaneous'),
 ('nm0067845', 'Sondos Belhassen', None, None, 'actress'),
 ('nm0067983', 'Krunoslav Belko', 1971.0, None, 'actor'),
 ('nm0068170', 'Dylan Bell', None, None, 'director,actor,producer'),
 ('nm0068657',
  'Philippe Bellaiche',
  None,
  None,
  'cinematographer,camera_department,producer'),
 ('nm0068874', 'Hava Kohav Beller', None, None, 'director,writer,producer'),
 ('nm0069131', 'Gregg Bello', None, None, 'actor,producer'),
 ('nm0069225', 'Gavin Bellour', None, None, 'actor,producer,composer'),
 ('nm0069605',
  'Bruno Beltramini',
  None,
  None,
  'cinematographer,visual_effects,camera_department'),
 ('nm0069757', 'Olga Belyavskaya', None, None, 'actress,miscellaneous'),
 ('nm0069990', 'Jorge Ben Jor', 1942.0, None, 'soundtrack,composer,actor'),
 ('nm0070216',
  'John Paul Fedele',
  None,
  None,
  'actor,cinematographer,special_effects'),
 ('nm0070482', 'Joel Bender', 1948.0, None, 'editor,director,writer'),
 ('nm0070822',
  'Terry Benedict',
  None,
  None,
  'producer,director,assistant_director'),
 ('nm0071116', 'Valérie Benguigui', 1961.0, 2013.0, 'actress,soundtrack'),
 ('nm0072456',
  'Chris Benson',
  1974.0,
  None,
  'cinematographer,camera_department,producer'),
 ('nm0072476', 'Doug Benson', 1962.0, None, 'actor,producer,writer'),
 ('nm0073061',
  'Roberto Benvenuti',
  None,
  None,
  'cinematographer,camera_department,miscellaneous'),
 ('nm0073146', 'Gina Lola Benzina', None, None, 'actress,make_up_department'),
 ('nm0073381', 'Roxana Berco', None, None, 'actress'),
 ('nm0073426', 'Laxmikant Berde', 1954.0, 2004.0, 'actor'),
 ('nm0074009', 'Richard Berge', None, None, 'producer,miscellaneous,writer'),
 ('nm0074445',
  'Jean-François Bergeron',
  None,
  None,
  'editor,editorial_department,actor'),
 ('nm0075049', 'Urban Bergsten', None, None, 'actor,writer,director'),
 ('nm0075666',
  'Joe Berlinger',
  1961.0,
  None,
  'producer,director,camera_department'),
 ('nm0076139', 'Andrée Bernard', 1966.0, None, 'actress'),
 ('nm0076559',
  'Carlos Bernases',
  None,
  None,
  'production_manager,producer,casting_department'),
 ('nm0077024', 'Daniel Bernstein', None, None, 'composer,sound_department'),
 ('nm0077067', 'Jamie Bernstein', 1952.0, None, 'director,actress,writer'),
 ('nm0080566',
  'Martín Bianchedi',
  1955.0,
  None,
  'composer,music_department,sound_department'),
 ('nm0080787', 'Dusty Bias', None, None, 'writer,director,producer'),
 ('nm0081060', 'Grace Cary Bickley', None, None, 'writer,actress,producer'),
 ('nm0081133',
  'Adrienne Biddle',
  1971.0,
  None,
  'producer,miscellaneous,director'),
 ('nm0081255', 'Andreas Bieber', 1966.0, None, 'actor'),
 ('nm0081516', 'Ric Esther Bienstock', None, None, 'producer,director,writer'),
 ('nm0081702', 'Claudio Bigagli', 1955.0, None, 'actor,writer,director'),
 ('nm0081735', 'Andrew Bigelow', None, None, 'actor,producer'),
 ('nm0082112', 'Jay Bilas', 1963.0, None, 'actor,producer'),
 ('nm0082154', 'Miro Bilbrough', None, None, 'miscellaneous,director,writer'),
 ('nm0082302', 'Billa', None, None, 'actor,music_department,stunts'),
 ('nm0082740', 'Shirin Bina', None, None, 'actress'),
 ('nm0083119', 'Avi Benjamin', None, None, 'composer,music_department'),
 ('nm0083271', 'Leila Birch', 1978.0, None, 'actress,miscellaneous,producer'),
 ('nm0083605', 'David Birkin', 1977.0, None, 'actor'),
 ('nm0083767', 'Fernando Birri', 1925.0, 2017.0, 'director,actor,writer'),
 ('nm0083851', 'Sam Bisbee', None, None, 'producer,composer,soundtrack'),
 ('nm0085193', 'Bill Black', 1926.0, 1965.0, 'actor,soundtrack'),
 ('nm0085316', 'James Black', 1962.0, None, 'actor,producer,director'),
 ('nm0086051', 'Bob Blagden', None, None, 'director,art_department,writer'),
 ('nm0086205', 'Bre Blair', 1980.0, None, 'actress'),
 ('nm0086611', 'Julia Blake', 1936.0, None, 'actress'),
 ('nm0086850', 'G. Robert Blakey', 1936.0, None, 'producer'),
 ('nm0087103', 'Saga Blanchard', None, None, 'miscellaneous,producer,actress'),
 ('nm0087190', 'Maurice Blanchot', 1907.0, 2003.0, 'writer'),
 ('nm0087222',
  'Alejandro Blanco Uribe',
  None,
  None,
  'composer,music_department,sound_department'),
 ('nm0087450', 'Mark Blaney', 1969.0, None, 'producer,miscellaneous'),
 ('nm0087595', 'Jamie Blanks', None, None, 'composer,director,editor'),
 ('nm0087913', 'Jean Blaute', 1952.0, None, 'composer,actor,music_department'),
 ('nm0087933',
  'Jacek Blawut',
  1950.0,
  None,
  'cinematographer,miscellaneous,director'),
 ('nm0088098', 'Jonah Blechman', 1975.0, None, 'actor,miscellaneous,producer'),
 ('nm0088531', 'Ryan Bliss', None, None, 'director,writer,producer'),
 ('nm0088888', 'Eric Blom', None, None, 'director,camera_department,writer'),
 ('nm0088949',
  'Lars Blomgren',
  None,
  None,
  'producer,location_management,production_manager'),
 ('nm0089850', 'Lars Blumers', None, None, 'director,writer,producer'),
 ('nm0089896', 'Colin Blunstone', 1945.0, None, 'soundtrack,actor'),
 ('nm0090420',
  'Alexander Boboschewski',
  1962.0,
  None,
  'camera_department,cinematographer,actor'),
 ('nm0090847',
  'Roberto Bodegas',
  1933.0,
  None,
  'director,assistant_director,writer'),
 ('nm0091773', 'Holt Boggs', 1971.0, None, 'actor,producer,writer'),
 ('nm0092307',
  'Nicolas de Boiscuillé',
  None,
  None,
  'production_designer,set_decorator,actor'),
 ('nm0092526',
  'David Christopher Loya',
  None,
  None,
  'producer,director,writer'),
 ('nm0093109', 'Don Bolles', 1956.0, None, 'actor,soundtrack,miscellaneous'),
 ('nm0093174', 'Ryan Bollman', 1972.0, None, 'actor'),
 ('nm0093284',
  'Aleksandr Bokovikov',
  None,
  None,
  'producer,actor,assistant_director'),
 ('nm0093589', 'Matt Bomer', 1977.0, None, 'actor,producer,soundtrack'),
 ('nm0093674', 'Arcangelo Bonaccorso', None, None, 'writer,director'),
 ('nm0094438', 'Tae-gyu Bong', None, None, 'actor'),
 ('nm0094612', 'Daryl Bonilla', 1975.0, None, 'actor,director'),
 ('nm0094754', 'Emmanuelle Bonmariage', None, None, 'actress,director'),
 ('nm0094756',
  'Manu Bonmariage',
  1941.0,
  None,
  'cinematographer,director,camera_department'),
 ('nm0095089',
  'Françoise Bonnot',
  1939.0,
  2018.0,
  'editor,actress,sound_department'),
 ('nm0096073', 'Óscar Borda', None, None, 'actor,music_department,soundtrack'),
 ('nm0096983',
  'Wes Borland',
  1975.0,
  None,
  'soundtrack,composer,music_department'),
 ('nm0097788', 'Stephan Bosch', None, None, 'actor,director,writer'),
 ('nm0097833', 'João Bosco', 1946.0, None, 'soundtrack,actor,composer'),
 ('nm0098327',
  'Andy Boswell',
  None,
  None,
  'actor,special_effects,art_department'),
 ('nm0098545', 'Marie Boti', None, None, 'director,writer'),
 ('nm0098583', 'Claudio Botosso', 1958.0, None, 'actor'),
 ('nm0099134', 'Jacques Boudet', None, None, 'actor'),
 ('nm0099797', 'Pascal Bourdiaux', None, None, 'director,editor'),
 ('nm0099841', 'Gilles Bourdos', 1963.0, None, 'writer,director'),
 ('nm0099922',
  'Pierre Bourgeois',
  None,
  None,
  'cinematographer,director,writer'),
 ('nm0099996',
  'Joelle Bourjolly',
  None,
  None,
  'writer,miscellaneous,camera_department'),
 ('nm0100311',
  'Daniel Bouthillette',
  None,
  None,
  'assistant_director,cinematographer,camera_department'),
 ('nm0100556', 'Raoul Bova', 1971.0, None, 'actor,producer,writer'),
 ('nm0100854', 'Jeremy Bowen', 1960.0, None, 'actor'),
 ('nm0100865',
  'Jon Bowen',
  1981.0,
  None,
  'camera_department,cinematographer,actor'),
 ('nm0101047',
  'David Bowers',
  None,
  None,
  'animation_department,director,writer'),
 ('nm0101055', 'George Bowers', 1944.0, 2012.0, 'editor,director,actor'),
 ('nm0101248', 'Peter Bowles', 1936.0, None, 'actor,writer,producer'),
 ('nm0101597', 'Armen Boyamyan', None, None, 'composer'),
 ('nm0101952', 'Wayne Boyd', None, None, 'actor,producer'),
 ('nm0102070', 'Manu Boyer', None, None, 'director,writer,camera_department'),
 ('nm0102744', 'Diana Bracho', 1944.0, None, 'actress'),
 ('nm0103187', 'Dan Bradley', None, None, 'stunts,assistant_director,actor'),
 ('nm0103262',
  'James Allen Bradley',
  None,
  None,
  'producer,miscellaneous,director'),
 ('nm0104185', 'Kicki Bramberg', 1955.0, None, 'actress'),
 ('nm0104309',
  'Joyce Branagh',
  1970.0,
  None,
  'actress,miscellaneous,assistant_director'),
 ('nm0104373', 'Taylor Branch', None, None, 'writer,producer'),
 ('nm0104567',
  'Madeline Brandeis',
  1897.0,
  1937.0,
  'producer,director,writer'),
 ('nm0105723', 'Bettina Braun', 1969.0, None, 'director,editor,writer'),
 ('nm0105779', 'Heinz-Josef Braun', 1957.0, None, 'actor'),
 ('nm0105914', 'Sharon Brauner', 1969.0, None, 'actress,producer,director'),
 ('nm0106040', 'Noelia Bravo Herrera', None, None, 'actress'),
 ('nm0106842', 'Neil Bregman', 1954.0, None, 'producer'),
 ('nm0106979', 'Michal Breitenwald', 1955.0, None, 'actor'),
 ('nm0107428', 'Joshua Earl Brennand', None, None, 'actor,writer,producer'),
 ('nm0108484',
  'Laurence Briaud',
  None,
  None,
  'editor,editorial_department,sound_department'),
 ('nm0109243',
  'Richard Briglia',
  None,
  None,
  'cinematographer,camera_department,producer'),
 ('nm0109400', 'Mariola Brillowska', 1961.0, None, 'director,writer,actress'),
 ('nm0110123',
  'Benjamin Britten',
  1913.0,
  1976.0,
  'soundtrack,music_department,composer'),
 ('nm0110262', 'Werner Brix', 1964.0, None, 'actor'),
 ('nm0111127',
  'Robert Bröllochs',
  None,
  None,
  'director,cinematographer,composer'),
 ('nm0111665', 'Simon Brook', None, None, 'director,writer,producer'),
 ('nm0111701', 'Haynes Brooke', None, None, 'actor,editor,director'),
 ('nm0112678', 'Christopher Broughton', None, None, 'actor,producer,director'),
 ('nm0112892',
  'Kelley Brower',
  None,
  None,
  'assistant_director,producer,director'),
 ('nm0113427', 'Don Brown', 1964.0, None, 'actor'),
 ('nm0113731', 'Iain Brown', None, None, 'producer,miscellaneous'),
 ('nm0113819', 'Jeffrey D. Brown', None, None, 'director,writer,producer'),
 ('nm0114399', 'Paul Brown', None, None, 'producer,writer,miscellaneous'),
 ('nm0114441', 'Philip Martin Brown', 1956.0, None, 'actor'),
 ('nm0114698', 'Stephen Joel Brown', None, None, 'producer,actor'),
 ('nm0115088',
  'Turner Browne',
  None,
  None,
  'cinematographer,producer,director'),
 ('nm0115143', 'Alistair Browning', 1954.0, 2019.0, 'actor'),
 ('nm0115234', 'Johnathan Brownlee', 1966.0, None, 'producer,writer,director'),
 ('nm0115262', 'Tony Brownrigg', 1968.0, None, 'actor,writer,director'),
 ('nm0115638',
  'Florentine Bruck',
  1958.0,
  None,
  'editor,assistant_director,miscellaneous'),
 ('nm0115956',
  'Reinier van Brummelen',
  None,
  None,
  'cinematographer,visual_effects,camera_department'),
 ('nm0116101', 'Frédéric Bruneel', None, None, 'producer,production_manager'),
 ('nm0116263', 'Francesco Bruni', 1961.0, None, 'writer,director,actor'),
 ('nm0116737',
  'Cory Brusseau',
  None,
  None,
  'editorial_department,actor,miscellaneous'),
 ('nm0116978', 'Lindsay Bryan', None, None, 'actress,composer'),
 ('nm0117863', 'Maria Grazia Buccella', 1940.0, None, 'actress,soundtrack'),
 ('nm0118047', 'Big Youth', 1949.0, None, 'soundtrack,actor'),
 ('nm0118573',
  'Betty A. Buckley',
  None,
  None,
  'producer,miscellaneous,production_manager'),
 ('nm0118711',
  'Cheryl Buckman',
  None,
  None,
  'editorial_department,editor,production_manager'),
 ('nm0118741', 'Andre Buckner', 1964.0, None, 'actor,producer,director'),
 ('nm0118975',
  'Tom Buderwitz',
  None,
  None,
  'production_designer,art_department,art_director'),
 ('nm0119109', 'Christiane Büchner', 1965.0, None, 'director,writer,editor'),
 ('nm0119287', 'Jeanette B. Milio', 1964.0, None, 'producer,writer,director'),
 ('nm0120025',
  'Kim Bullard',
  None,
  None,
  'composer,soundtrack,music_department'),
 ('nm0120263', 'Bruno Bulté', None, None, 'actor'),
 ('nm0120284', 'Andy Bumatai', None, None, 'actor'),
 ('nm0120332', 'David Bunce', None, None, 'actor,director,producer'),
 ('nm0120366', 'Ralph Bunche', 1904.0, 1971.0, None),
 ('nm0120814', 'Noël Burch', 1932.0, None, 'director,writer,cinematographer'),
 ('nm0120816', 'Ron Burch', None, None, 'producer,writer'),
 ('nm0121620', 'Carlease Burke', None, None, 'actress,producer'),
 ('nm0121708', 'James Burke', 1936.0, None, 'writer,miscellaneous,producer'),
 ('nm0121731', 'Joe Michael Burke', 1973.0, None, 'actor,producer'),
 ('nm0121903', 'Willi Burke', None, None, 'actress'),
 ('nm0121966',
  'Helen McCready',
  1961.0,
  None,
  'casting_director,casting_department,actress'),
 ('nm0122007',
  'Jonathan Burkhart',
  None,
  None,
  'producer,camera_department,production_manager'),
 ('nm0122344',
  'Charles Burnett',
  1944.0,
  None,
  'director,writer,cinematographer'),
 ('nm0122379', 'Jim Burnett', None, None, 'writer,producer,miscellaneous'),
 ('nm0122635', 'David Burns', 1977.0, None, 'actor,producer'),
 ('nm0122636',
  'David G. Burns',
  None,
  None,
  'composer,music_department,sound_department'),
 ('nm0122703', 'James C. Burns', 1959.0, None, 'actor,producer,writer'),
 ('nm0123058', 'Dave Burrell', None, None, 'composer'),
 ('nm0123074',
  'Kenny Burrell',
  1931.0,
  None,
  'soundtrack,composer,music_department'),
 ('nm0123385', 'Sid Burston', None, None, 'actor,producer,director'),
 ('nm0123653',
  'Linda Burton',
  None,
  None,
  'production_designer,art_department,costume_department'),
 ('nm0123896',
  'Gerald Busby',
  1935.0,
  None,
  'composer,actor,music_department'),
 ('nm0124502', 'Mathieu Bisson', None, None, 'actor,sound_department'),
 ('nm0124796',
  'Riki Butland',
  None,
  None,
  'camera_department,cinematographer'),
 ('nm0125336', 'Jez Butterworth', 1969.0, None, 'writer,producer,actor'),
 ('nm0125588', 'Agata Buzek', 1976.0, None, 'actress,soundtrack'),
 ('nm0125608', 'Natalya Buzko', 1963.0, None, 'actress'),
 ('nm0125661',
  'Paolo Buzzurro',
  None,
  None,
  'miscellaneous,actor,production_manager'),
 ('nm0126173', 'Elianne Byrne', None, None, 'actress'),
 ('nm0126478', 'Margaretha Byström', 1937.0, None, 'actress'),
 ('nm0127067', 'Wolfgang Böhmer', 1959.0, None, 'composer,actor'),
 ('nm0127202', 'Sigve Bøe', 1948.0, None, 'actor,writer,soundtrack'),
 ('nm0127313', 'Andrea Bürgin', 1957.0, None, 'actress'),
 ('nm0128212', 'Anne-Marie Cadieux', None, None, 'actress,director,writer'),
 ('nm0128230', 'Elia Enid Cadilla', 1944.0, None, 'actress,director'),
 ('nm0128328', 'Gary Cady', 1960.0, None, 'actor'),
 ('nm0128464', 'Eliane Caffé', 1961.0, None, 'director,writer'),
 ('nm0128550',
  'John Caglione Jr.',
  1958.0,
  None,
  'make_up_department,special_effects'),
 ('nm0128937',
  'Michael Cain',
  None,
  None,
  'producer,production_manager,location_management'),
 ('nm0129807', 'Zoe Caldwell', 1933.0, None, 'actress'),
 ('nm0130385', 'Monica Calle', 1966.0, None, 'actress'),
 ('nm0130957', 'Juan Manuel Calvo', None, None, 'director,writer,editor'),
 ('nm0130977',
  'Néstor Calvo',
  None,
  None,
  'cinematographer,camera_department'),
 ('nm0130991', 'Salvador Calvo', 1970.0, None, 'assistant_director,director'),
 ('nm0131252', 'Iberê Camargo', 1914.0, 1994.0, 'actor'),
 ('nm0131347', 'James Camblin', None, None, 'actor'),
 ('nm0131563',
  'Duncan Cameron',
  None,
  None,
  'cinematographer,editor,assistant_director'),
 ('nm0132168', 'John W. Campbell Jr.', 1910.0, 1971.0, 'writer'),
 ('nm0132265',
  'Bryce Campbell',
  None,
  None,
  'location_management,camera_department,actor'),
 ('nm0132340',
  'Cosmo Campbell',
  None,
  None,
  'camera_department,cinematographer'),
 ('nm0132631', 'Ken Campbell', 1941.0, 2008.0, 'actor,writer,director'),
 ('nm0132962',
  'Luc Campeau',
  None,
  None,
  'assistant_director,producer,production_manager'),
 ('nm0133253', 'Jorge Campos', None, None, 'director,writer,miscellaneous'),
 ('nm0133426',
  'Mario Camus',
  1935.0,
  None,
  'director,writer,assistant_director'),
 ('nm0133658', 'Aurora Cancian', 1949.0, None, 'actress,miscellaneous'),
 ('nm0133843', 'Vlastimil Canek', 1931.0, None, 'actor'),
 ('nm0134357', 'Roberto Cano', 1973.0, None, 'actor'),
 ('nm0135394',
  'Vinicio Capossela',
  1965.0,
  None,
  'soundtrack,writer,composer'),
 ('nm0135667', 'Anita Caprioli', 1973.0, None, 'actress'),
 ('nm0135952', 'Nae Caranfil', 1960.0, None, 'writer,director,actor'),
 ('nm0136775', 'Peter Care', 1953.0, None, 'director,writer,cinematographer'),
 ('nm0136927', 'Danny Carey', 1961.0, None, 'composer,actor,music_department'),
 ('nm0136996',
  'Mark Carey',
  None,
  None,
  'cinematographer,camera_department,assistant_director'),
 ('nm0137365', 'Catherine Carlen', 1953.0, None, 'actress,producer,director'),
 ('nm0138701',
  'Valentina Carnelutti',
  1973.0,
  None,
  'actress,writer,producer'),
 ('nm0138708', 'Kathryn Carner', None, None, 'actress,producer,director'),
 ('nm0138966', 'Jean Carol', None, None, 'actress,producer'),
 ('nm0139605',
  'Neal Marshall Stevens',
  None,
  None,
  'miscellaneous,writer,director'),
 ('nm0140087',
  'Ricardo Carrasco',
  1960.0,
  None,
  'director,cinematographer,writer'),
 ('nm0140179',
  'Ricardo Carrión',
  None,
  None,
  'actor,composer,music_department'),
 ('nm0140510', 'Marcela Carrillo', None, None, 'actress'),
 ('nm0141324', 'Silas Carson', 1965.0, None, 'actor'),
 ('nm0141450', 'Alex Carter', 1964.0, None, 'actor'),
 ('nm0141682', 'Jason Carter', 1960.0, None, 'actor,producer,writer'),
 ('nm0142808', 'Diego Casale', 1971.0, None, 'actor'),
 ('nm0143819', 'Michaela Caspar', 1960.0, None, 'actress,director,writer'),
 ('nm0143873', 'Dorin Caspi', 1953.0, None, 'actress'),
 ('nm0144039', 'Cécile Cassel', 1982.0, None, 'actress,soundtrack'),
 ('nm0144291',
  'Bill Cassinelli',
  1969.0,
  None,
  'actor,writer,special_effects'),
 ('nm0144887',
  'Virgílio Castelo',
  1953.0,
  None,
  'actor,production_manager,miscellaneous'),
 ('nm0145518', 'David Castro', None, None, 'actor,director,writer'),
 ('nm0145813', 'Bobby Catalano', None, None, 'actor'),
 ('nm0145951', 'Antonio Catania', 1952.0, None, 'actor'),
 ('nm0146341', 'Peter Cattaneo', 1964.0, None, 'director,writer,editor'),
 ('nm0146812',
  'Megan Cavallari',
  None,
  None,
  'composer,music_department,soundtrack'),
 ('nm0147332', 'Óscar del Caz', None, None, 'producer,director,writer'),
 ('nm0147975', 'Jaime Celedón', None, None, 'actor'),
 ('nm0148234', 'Julia Cencig', 1972.0, None, 'actress,soundtrack'),
 ('nm0148235', 'Michael Cencig', None, None, 'producer,director,writer'),
 ('nm0149083', 'Ceesepe', 1958.0, 2018.0, 'miscellaneous,director,actor'),

In [21]:
# Create a Pandas DataFrame from the data in the 'persons' table
IMDB_persons = pd.read_sql_query("SELECT * FROM persons", conn)
IMDB_persons

,person_id,primary_name,birth_year,death_year,primary_profession
0,nm0061671,Mary Ellen Bauder,NaN,NaN,"miscellaneous,production_manager,producer"
1,nm0061865,Joseph Bauer,NaN,NaN,"composer,music_department,sound_department"
2,nm0062070,Bruce Baum,NaN,NaN,"miscellaneous,actor,writer"
3,nm0062195,Axel Baumann,NaN,NaN,"camera_department,cinematographer,art_department"
4,nm0062798,Pete Baxter,NaN,NaN,"production_designer,art_department,set_decorator"
...,...,...,...,...,...
606643,nm9990381,Susan Grobes,NaN,NaN,actress
606644,nm9990690,Joo Yeon So,NaN,NaN,actress
606645,nm9991320,Madeline Smith,NaN,NaN,actress
606646,nm9991786,Michelle Modigliani,NaN,NaN,producer
606647,nm9993380,Pegasus Envoyé,NaN,NaN,"director,actor,writer"

In [29]:
# Create a Pandas DataFrame from the data in the 'principals' table
IMDB_principals = pd.read_sql_query("SELECT * FROM principals", conn)
IMDB_principals

,movie_id,ordering,person_id,category,job,characters
0,tt0111414,1,nm0246005,actor,None,"[""The Man""]"
1,tt0111414,2,nm0398271,director,None,None
2,tt0111414,3,nm3739909,producer,producer,None
3,tt0323808,10,nm0059247,editor,None,None
4,tt0323808,1,nm3579312,actress,None,"[""Beth Boothby""]"
...,...,...,...,...,...,...
1028181,tt9692684,1,nm0186469,actor,None,"[""Ebenezer Scrooge""]"
1028182,tt9692684,2,nm4929530,self,None,"[""Herself"",""Regan""]"
1028183,tt9692684,3,nm10441594,director,None,None
1028184,tt9692684,4,nm6009913,writer,writer,None
1028185,tt9692684,5,nm10441595,producer,producer,None

In [30]:
# Create a Pandas DataFrame from the data in the 'known_for' table
IMDB_known_for = pd.read_sql_query("SELECT * FROM known_for", conn)
IMDB_known_for

         person_id   movie_id
0        nm0061671  tt0837562
1        nm0061671  tt2398241
2        nm0061671  tt0844471
3        nm0061671  tt0118553
4        nm0061865  tt0896534
...            ...        ...
1638255  nm9990690  tt9090932
1638256  nm9990690  tt8737130
1638257  nm9991320  tt8734436
1638258  nm9991320  tt9615610
1638259  nm9993380  tt8743182

[1638260 rows x 2 columns]

In [33]:
# Create a Pandas DataFrame from the data in the 'directors' table
IMDB_directors = pd.read_sql_query("SELECT * FROM directors", conn)
IMDB_directors

         movie_id   person_id
0       tt0285252   nm0899854
1       tt0462036   nm1940585
2       tt0835418   nm0151540
3       tt0835418   nm0151540
4       tt0878654   nm0089502
...           ...         ...
291169  tt8999974  nm10122357
291170  tt9001390   nm6711477
291171  tt9001494  nm10123242
291172  tt9001494  nm10123248
291173  tt9004986   nm4993825

[291174 rows x 2 columns]

In [32]:
# Create a Pandas DataFrame from the data in the 'writers' table
IMDB_writers = pd.read_sql_query("SELECT * FROM writers", conn)
IMDB_writers

         movie_id   person_id
0       tt0285252   nm0899854
1       tt0438973   nm0175726
2       tt0438973   nm1802864
3       tt0462036   nm1940585
4       tt0835418   nm0310087
...           ...         ...
255868  tt8999892  nm10122246
255869  tt8999974  nm10122357
255870  tt9001390   nm6711477
255871  tt9004986   nm4993825
255872  tt9010172   nm8352242

[255873 rows x 2 columns]

In [34]:
# Create a Pandas DataFrame from the data in the 'movie_basics' table
IMDB_movie_basics= pd.read_sql_query("SELECT * FROM movie_basics", conn)
IMDB_movie_basics

,movie_id,primary_title,original_title,start_year,runtime_minutes,genres
0,tt0063540,Sunghursh,Sunghursh,2013,175.0,"Action,Crime,Drama"
1,tt0066787,One Day Before the Rainy Season,Ashad Ka Ek Din,2019,114.0,"Biography,Drama"
2,tt0069049,The Other Side of the Wind,The Other Side of the Wind,2018,122.0,Drama
3,tt0069204,Sabse Bada Sukh,Sabse Bada Sukh,2018,NaN,"Comedy,Drama"
4,tt0100275,The Wandering Soap Opera,La Telenovela Errante,2017,80.0,"Comedy,Drama,Fantasy"
...,...,...,...,...,...,...
146139,tt9916538,Kuambil Lagi Hatiku,Kuambil Lagi Hatiku,2019,123.0,Drama
146140,tt9916622,Rodolpho Teóphilo - O Legado de um Pioneiro,Rodolpho Teóphilo - O Legado de um Pioneiro,2015,NaN,Documentary
146141,tt9916706,Dankyavar Danka,Dankyavar Danka,2013,NaN,Comedy
146142,tt9916730,6 Gunn,6 Gunn,2017,116.0,None
146143,tt9916754,Chico Albuquerque - Revelações,Chico Albuquerque - Revelações,2013,NaN,Documentary

In [35]:
# Create a Pandas DataFrame from the data in the 'movie_ratings' table
IMDB_movie_ratings= pd.read_sql_query("SELECT * FROM movie_ratings", conn)
IMDB_movie_ratings

         movie_id  averagerating  numvotes
0      tt10356526            8.3        31
1      tt10384606            8.9       559
2       tt1042974            6.4        20
3       tt1043726            4.2     50352
4       tt1060240            6.5        21
...           ...            ...       ...
73851   tt9805820            8.1        25
73852   tt9844256            7.5        24
73853   tt9851050            4.7        14
73854   tt9886934            7.0         5
73855   tt9894098            6.3       128

[73856 rows x 3 columns]

In [36]:
# Create a Pandas DataFrame from the data in the 'movie_akas' table
IMDB_movie_akas= pd.read_sql_query("SELECT * FROM movie_akas", conn)
IMDB_movie_akas

,movie_id,ordering,title,region,language,types,attributes,is_original_title
0,tt0369610,10,Джурасик свят,BG,bg,None,None,0.0
1,tt0369610,11,Jurashikku warudo,JP,None,imdbDisplay,None,0.0
2,tt0369610,12,Jurassic World: O Mundo dos Dinossauros,BR,None,imdbDisplay,None,0.0
3,tt0369610,13,O Mundo dos Dinossauros,BR,None,None,short title,0.0
4,tt0369610,14,Jurassic World,FR,None,imdbDisplay,None,0.0
...,...,...,...,...,...,...,...,...
331698,tt9827784,2,Sayonara kuchibiru,None,None,original,None,1.0
331699,tt9827784,3,Farewell Song,XWW,en,imdbDisplay,None,0.0
331700,tt9880178,1,La atención,None,None,original,None,1.0
331701,tt9880178,2,La atención,ES,None,None,None,0.0
331702,tt9880178,3,The Attention,XWW,en,imdbDisplay,None,0.0

Dealing with CSV DATA SETS

In [3]:
#Importing the movie budgets csv(tn.movie_budgets)
import pandas as pd
movie_budgets =pd.read_csv(r'C:\Users\PC\Downloads\Moringa School\dsc-phase-1-project-v2-4\zippedData\tn.movie_budgets.csv')
movie_budgets

,id,release_date,movie,production_budget,domestic_gross,worldwide_gross
0,1,"Dec 18, 2009",Avatar,"$425,000,000","$760,507,625","$2,776,345,279"
1,2,"May 20, 2011",Pirates of the Caribbean: On Stranger Tides,"$410,600,000","$241,063,875","$1,045,663,875"
2,3,"Jun 7, 2019",Dark Phoenix,"$350,000,000","$42,762,350","$149,762,350"
3,4,"May 1, 2015",Avengers: Age of Ultron,"$330,600,000","$459,005,868","$1,403,013,963"
4,5,"Dec 15, 2017",Star Wars Ep. VIII: The Last Jedi,"$317,000,000","$620,181,382","$1,316,721,747"
...,...,...,...,...,...,...
5777,78,"Dec 31, 2018",Red 11,"$7,000",$0,$0
5778,79,"Apr 2, 1999",Following,"$6,000","$48,482","$240,495"
5779,80,"Jul 13, 2005",Return to the Land of Wonders,"$5,000","$1,338","$1,338"
5780,81,"Sep 29, 2015",A Plague So Pleasant,"$1,400",$0,$0
5781,82,"Aug 5, 2005",My Date With Drew,"$1,100","$181,041","$181,041"

In [5]:
#Importing the tmdb.movies.csv( tmdb.movies)
tmdb_movies =pd.read_csv(r'C:\Users\PC\Downloads\Moringa School\dsc-phase-1-project-v2-4\zippedData\tmdb.movies.csv')
tmdb_movies

,Unnamed: 0,genre_ids,id,original_language,original_title,popularity,release_date,title,vote_average,vote_count
0,0,"[12, 14, 10751]",12444,en,Harry Potter and the Deathly Hallows: Part 1,33.533,2010-11-19,Harry Potter and the Deathly Hallows: Part 1,7.7,10788
1,1,"[14, 12, 16, 10751]",10191,en,How to Train Your Dragon,28.734,2010-03-26,How to Train Your Dragon,7.7,7610
2,2,"[12, 28, 878]",10138,en,Iron Man 2,28.515,2010-05-07,Iron Man 2,6.8,12368
3,3,"[16, 35, 10751]",862,en,Toy Story,28.005,1995-11-22,Toy Story,7.9,10174
4,4,"[28, 878, 12]",27205,en,Inception,27.920,2010-07-16,Inception,8.3,22186
...,...,...,...,...,...,...,...,...,...,...
26512,26512,"[27, 18]",488143,en,Laboratory Conditions,0.600,2018-10-13,Laboratory Conditions,0.0,1
26513,26513,"[18, 53]",485975,en,_EXHIBIT_84xxx_,0.600,2018-05-01,_EXHIBIT_84xxx_,0.0,1
26514,26514,"[14, 28, 12]",381231,en,The Last One,0.600,2018-10-01,The Last One,0.0,1
26515,26515,"[10751, 12, 28]",366854,en,Trailer Made,0.600,2018-06-22,Trailer Made,0.0,1
26516,26516,"[53, 27]",309885,en,The Church,0.600,2018-10-05,The Church,0.0,1

In [6]:
#Importing the bom.movie_gross.csv
movie_gross =pd.read_csv(r'C:\Users\PC\Downloads\Moringa School\dsc-phase-1-project-v2-4\zippedData\bom.movie_gross.csv')
movie_gross

,title,studio,domestic_gross,foreign_gross,year
0,Toy Story 3,BV,415000000.0,652000000,2010
1,Alice in Wonderland (2010),BV,334200000.0,691300000,2010
2,Harry Potter and the Deathly Hallows Part 1,WB,296000000.0,664300000,2010
3,Inception,WB,292600000.0,535700000,2010
4,Shrek Forever After,P/DW,238700000.0,513900000,2010
...,...,...,...,...,...
3382,The Quake,Magn.,6200.0,NaN,2018
3383,Edward II (2018 re-release),FM,4800.0,NaN,2018
3384,El Pacto,Sony,2500.0,NaN,2018
3385,The Swan,Synergetic,2400.0,NaN,2018
3386,An Actor Prepares,Grav.,1700.0,NaN,2018

In [9]:
# Use the read_csv function with the delimiter parameter set to '\t' to specify the TSV format.
#Importing the movie_info(rt.movie_info)
movie_info =pd.read_csv(r'C:\Users\PC\Downloads\Moringa School\dsc-phase-1-project-v2-4\zippedData\rt.movie_info.tsv',delimiter='\t')
movie_info

,id,synopsis,rating,genre,director,writer,theater_date,dvd_date,currency,box_office,runtime,studio
0,1,"This gritty, fast-paced, and innovative police...",R,Action and Adventure|Classics|Drama,William Friedkin,Ernest Tidyman,"Oct 9, 1971","Sep 25, 2001",NaN,NaN,104 minutes,NaN
1,3,"New York City, not-too-distant-future: Eric Pa...",R,Drama|Science Fiction and Fantasy,David Cronenberg,David Cronenberg|Don DeLillo,"Aug 17, 2012","Jan 1, 2013",$,"600,000",108 minutes,Entertainment One
2,5,Illeana Douglas delivers a superb performance ...,R,Drama|Musical and Performing Arts,Allison Anders,Allison Anders,"Sep 13, 1996","Apr 18, 2000",NaN,NaN,116 minutes,NaN
3,6,Michael Douglas runs afoul of a treacherous su...,R,Drama|Mystery and Suspense,Barry Levinson,Paul Attanasio|Michael Crichton,"Dec 9, 1994","Aug 27, 1997",NaN,NaN,128 minutes,NaN
4,7,NaN,NR,Drama|Romance,Rodney Bennett,Giles Cooper,NaN,NaN,NaN,NaN,200 minutes,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1555,1996,Forget terrorists or hijackers -- there's a ha...,R,Action and Adventure|Horror|Mystery and Suspense,NaN,NaN,"Aug 18, 2006","Jan 2, 2007",$,"33,886,034",106 minutes,New Line Cinema
1556,1997,The popular Saturday Night Live sketch was exp...,PG,Comedy|Science Fiction and Fantasy,Steve Barron,Terry Turner|Tom Davis|Dan Aykroyd|Bonnie Turner,"Jul 23, 1993","Apr 17, 2001",NaN,NaN,88 minutes,Paramount Vantage
1557,1998,"Based on a novel by Richard Powell, when the l...",G,Classics|Comedy|Drama|Musical and Performing Arts,Gordon Douglas,NaN,"Jan 1, 1962","May 11, 2004",NaN,NaN,111 minutes,NaN
1558,1999,The Sandlot is a coming-of-age story about a g...,PG,Comedy|Drama|Kids and Family|Sports and Fitness,David Mickey Evans,David Mickey Evans|Robert Gunter,"Apr 1, 1993","Jan 29, 2002",NaN,NaN,101 minutes,NaN
1559,2000,"Suspended from the force, Paris cop Hubert is ...",R,Action and Adventure|Art House and Internation...,NaN,Luc Besson,"Sep 27, 2001","Feb 11, 2003",NaN,NaN,94 minutes,Columbia Pictures

In [14]:
# Use the read_csv function with the delimiter parameter set to '\t' to specify the TSV format.
#Importing the movie_info(rt.movie_info)
movie_reviews =pd.read_csv(r'C:\Users\PC\Downloads\Moringa School\dsc-phase-1-project-v2-4\zippedData\rt.reviews.tsv',delimiter='\t',encoding='latin-1')
movie_reviews

,id,review,rating,fresh,critic,top_critic,publisher,date
0,3,A distinctly gallows take on contemporary fina...,3/5,fresh,PJ Nabarro,0,Patrick Nabarro,"November 10, 2018"
1,3,It's an allegory in search of a meaning that n...,NaN,rotten,Annalee Newitz,0,io9.com,"May 23, 2018"
2,3,... life lived in a bubble in financial dealin...,NaN,fresh,Sean Axmaker,0,Stream on Demand,"January 4, 2018"
3,3,Continuing along a line introduced in last yea...,NaN,fresh,Daniel Kasman,0,MUBI,"November 16, 2017"
4,3,... a perverse twist on neorealism...,NaN,fresh,NaN,0,Cinema Scope,"October 12, 2017"
...,...,...,...,...,...,...,...,...
54427,2000,The real charm of this trifle is the deadpan c...,NaN,fresh,Laura Sinagra,1,Village Voice,"September 24, 2002"
54428,2000,NaN,1/5,rotten,Michael Szymanski,0,Zap2it.com,"September 21, 2005"
54429,2000,NaN,2/5,rotten,Emanuel Levy,0,EmanuelLevy.Com,"July 17, 2005"
54430,2000,NaN,2.5/5,rotten,Christopher Null,0,Filmcritic.com,"September 7, 2003"
54431,2000,NaN,3/5,fresh,Nicolas Lacroix,0,Showbizz.net,"November 12, 2002"

You can link the necessary Table IDs and Do Your EDA from here ..............................